# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20170826_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='advisor_email',
            field=models.CharField(default='null@issaquah.wednet.edu', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='advisor_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='club',
            name='asb_account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=200),
        ),
    ]
