# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20170826_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_app.Club', verbose_name='Club'),
            preserve_default=False,
        ),
    ]
